# https://taskfile.dev

version: "3"

tasks:
  install:
    internal: true
    cmds:
      - poetry install
  poetry:coverage:
    internal: true
    cmds:
      - poetry run coverage xml
      - poetry run coverage lcov
  poetry:test:all:
    cmds:
      - poetry run pytest
      - task: poetry:coverage
    silent: true
  poetry:test:ci:
    cmds:
      - poetry run pytest -m "unit or component"
      - task: poetry:coverage
    silent: true
    deps:
      - install
  poetry:test:unit:
    cmds:
      - poetry run pytest -m unit
      - task: poetry:coverage
    silent: true
    deps:
      - install
  poetry:test:component:
    cmds:
      - poetry run pytest -m component
      - task: poetry:coverage
    silent: true
    deps:
      - install
  poetry:test:integration:
    cmds:
      - poetry run pytest -m integration
      - poetry run coverage xml
    silent: true
    deps:
      - install
  poetry:build:
    cmds:
      - poetry build
    silent: true
    deps:
      - install
  poetry:run:
    cmds:
      - poetry run uvicorn --app-dir pyconarr main:app --reload --log-config=config/log.yaml
    silent: true
    interactive: true
    deps:
      - install
  megalinter:test:
    cmds:
      - docker run --pull=always --rm -v ${LOCALWORKSPACE}:/tmp/lint -w /tmp/lint oxsecurity/megalinter:v7
    silent: true
  bruno:all:
    cmds:
      - task: bruno:test:PR
  bruno:test:PR:
    dir: bruno/pyconarr
    cmds:
      - bru run --env "Jellyfin_PR"
