---
services:
  pyconnar:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    command: /bin/sh -c "sleep infinity"
    env_file:
      - devcontainer.env
  wiremock:
    image: wiremock/wiremock
    command: "--verbose"
    volumes:
      - ../wiremock:/home/wiremock
