---
version: "3"

services:
  pyconnar:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    command: /bin/sh -c "sleep infinity"
    network_mode: service:spring-boot-admin
  spring-boot-admin:
    image: michayaak/spring-boot-admin:2.3.0
