# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
---
name: Renovate Bot GitHub Action
run-name: Renovate Bot GitHub Action
permissions:
  contents: read
  actions: read
  checks: read

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 * * * *"
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v40.1.2
